import { defineAsyncComponent } from 'vue'
import type { ComponentDefinition } from '../types'

export const chinaMapDefinition: ComponentDefinition = {
  type: 'china-map',
  meta: {
    name: '中国地图',
    category: 'chart',
    icon: 'Location',
    defaultWidth: 500,
    defaultHeight: 400,
  },
  widget: defineAsyncComponent(() => import('./Widget.vue')),
  propsSchema: [
    { key: 'titleShow', label: '显示标题', type: 'switch', default: false, group: '标题' },
    {
      key: 'titleText',
      label: '标题文本',
      type: 'input',
      default: '中国地图',
      group: '标题',
      visibleWhen: { field: 'titleShow', truthy: true },
    },
    {
      key: 'mapColor',
      label: '区域颜色',
      type: 'colorpicker',
      default: '#1e293b',
      group: '区域',
      tip: '地图区域默认色',
    },
    {
      key: 'mapBorderColor',
      label: '省界颜色',
      type: 'colorpicker',
      default: '#475569',
      group: '区域',
      tip: '省界颜色',
    },
    {
      key: 'mapBorderWidth',
      label: '省界宽度',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.5,
      default: 0.5,
      group: '区域',
    },
    {
      key: 'emphasisColor',
      label: '高亮颜色',
      type: 'colorpicker',
      default: '#0e7490',
      group: '区域',
      tip: '高亮色',
    },
    {
      key: 'visualOn',
      label: '视觉映射',
      type: 'switch',
      default: true,
      group: '视觉映射',
      tip: '按数值着色',
    },
    {
      key: 'visualFrom',
      label: '低值色',
      type: 'colorpicker',
      default: '#fef3c7',
      group: '视觉映射',
      tip: '低值色',
      visibleWhen: { field: 'visualOn', truthy: true },
    },
    {
      key: 'visualTo',
      label: '高值色',
      type: 'colorpicker',
      default: '#dc2626',
      group: '视觉映射',
      tip: '高值色',
      visibleWhen: { field: 'visualOn', truthy: true },
    },
    {
      key: 'labelShow',
      label: '显示标签',
      type: 'switch',
      default: false,
      group: '标签',
      tip: '显示省份名',
    },
    { key: 'labelColor', label: '标签颜色', type: 'colorpicker', default: '#e2e8f0', group: '标签' },
  ],
  extraDefaults: {
    data: [
      { name: '北京', value: 54 },
      { name: '天津', value: 38 },
      { name: '河北', value: 79 },
      { name: '山西', value: 32 },
      { name: '内蒙古', value: 25 },
      { name: '辽宁', value: 58 },
      { name: '吉林', value: 30 },
      { name: '黑龙江', value: 34 },
      { name: '上海', value: 88 },
      { name: '江苏', value: 95 },
      { name: '浙江', value: 92 },
      { name: '安徽', value: 50 },
      { name: '福建', value: 62 },
      { name: '江西', value: 36 },
      { name: '山东', value: 86 },
      { name: '河南', value: 60 },
      { name: '湖北', value: 55 },
      { name: '湖南', value: 48 },
      { name: '广东', value: 98 },
      { name: '广西', value: 35 },
      { name: '海南', value: 18 },
      { name: '重庆', value: 42 },
      { name: '四川', value: 65 },
      { name: '贵州', value: 28 },
      { name: '云南', value: 40 },
      { name: '西藏', value: 8 },
      { name: '陕西', value: 45 },
      { name: '甘肃', value: 22 },
      { name: '青海', value: 12 },
      { name: '宁夏', value: 15 },
      { name: '新疆', value: 30 },
      { name: '台湾', value: 0 },
      { name: '香港', value: 0 },
      { name: '澳门', value: 0 },
    ],
  },
  defaultStyle: {},
  supportsDataBinding: true,
}

export default chinaMapDefinition
