import { defineAsyncComponent } from 'vue'
import type { ComponentDefinition } from '../types'

export const wordCloudDefinition: ComponentDefinition = {
  type: 'word-cloud',
  meta: {
    name: '词云',
    category: 'chart',
    icon: 'Histogram',
    defaultWidth: 400,
    defaultHeight: 300,
  },
  widget: defineAsyncComponent(() => import('./Widget.vue')),
  propsSchema: [
    { key: 'titleShow', label: '显示标题', type: 'switch', default: false, group: '标题' },
    {
      key: 'titleText',
      label: '标题文本',
      type: 'input',
      default: '词云',
      group: '标题',
      visibleWhen: { field: 'titleShow', truthy: true },
    },
    {
      key: 'minFontSize',
      label: '最小字号',
      type: 'slider',
      min: 10,
      max: 30,
      default: 12,
      group: '字体',
      tip: '最小词字号',
    },
    {
      key: 'maxFontSize',
      label: '最大字号',
      type: 'slider',
      min: 30,
      max: 80,
      default: 48,
      group: '字体',
      tip: '最大词字号',
    },
    {
      key: 'textColor',
      label: '主文字色',
      type: 'colorpicker',
      default: '#22d3ee',
      group: '颜色',
      tip: '主文字色',
    },
    {
      key: 'textColor2',
      label: '次文字色',
      type: 'colorpicker',
      default: '#67e8f9',
      group: '颜色',
      tip: '次文字色',
    },
    {
      key: 'textColor3',
      label: '辅文字色',
      type: 'colorpicker',
      default: '#a5f3fc',
      group: '颜色',
      tip: '辅文字色',
    },
    { key: 'rotate', label: '允许旋转', type: 'switch', default: true, group: '布局', tip: '允许旋转' },
    {
      key: 'rotateAngles',
      label: '旋转角度',
      type: 'select',
      options: [
        { label: '0/90度', value: '0,90' },
        { label: '0/45/90度', value: '0,45,90,135' },
        { label: '仅0度', value: '0' },
        { label: '仅90度', value: '90' },
      ],
      default: '0,90',
      group: '布局',
    },
    {
      key: 'gridSize',
      label: '词间距',
      type: 'slider',
      min: 4,
      max: 20,
      default: 8,
      group: '布局',
      tip: '词间距(px)',
    },
  ],
  extraDefaults: {
    words: [
      { name: '数据分析', value: 100 },
      { name: '可视化', value: 90 },
      { name: '大屏', value: 85 },
      { name: 'BI', value: 80 },
      { name: ' dashboard', value: 75 },
      { name: '实时', value: 70 },
      { name: '监控', value: 65 },
      { name: '告警', value: 60 },
      { name: '趋势', value: 55 },
      { name: '预测', value: 50 },
      { name: 'AI', value: 48 },
      { name: '机器学习', value: 45 },
      { name: '云原生', value: 42 },
      { name: '微服务', value: 40 },
      { name: '容器化', value: 38 },
      { name: 'DevOps', value: 35 },
      { name: '中台', value: 32 },
      { name: '低代码', value: 30 },
      { name: '物联网', value: 28 },
      { name: '5G', value: 26 },
      { name: '区块链', value: 24 },
      { name: '元宇宙', value: 22 },
    ],
  },
  defaultStyle: {},
  supportsDataBinding: true,
}

export default wordCloudDefinition
