import type { ComponentMeta, ComponentType } from '@/views/bi-editor/types'

export const COMPONENT_META: Record<ComponentType, ComponentMeta> = {
  text: {
    type: 'text',
    name: '文本',
    category: 'basic',
    icon: 'Document',
    defaultWidth: 120,
    defaultHeight: 40,
    defaultProps: { text: '文本内容', fontSize: 14, color: '#333333' },
    defaultStyle: {},
  },
  image: {
    type: 'image',
    name: '图片',
    category: 'basic',
    icon: 'Picture',
    defaultWidth: 160,
    defaultHeight: 120,
    defaultProps: { src: '', alt: '' },
    defaultStyle: {},
  },
  rect: {
    type: 'rect',
    name: '矩形',
    category: 'basic',
    icon: 'FullScreen',
    defaultWidth: 100,
    defaultHeight: 80,
    defaultProps: { borderRadius: 0 },
    defaultStyle: { backgroundColor: '#E5E7EB' },
  },
  line: {
    type: 'line',
    name: '直线',
    category: 'basic',
    icon: 'Minus',
    defaultWidth: 200,
    defaultHeight: 2,
    defaultProps: { direction: 'horizontal' },
    defaultStyle: { backgroundColor: '#999999' },
  },
  'bar-chart': {
    type: 'bar-chart',
    name: '柱状图',
    category: 'chart',
    icon: 'DataLine',
    defaultWidth: 400,
    defaultHeight: 300,
    defaultProps: { title: '柱状图', data: [] },
    defaultStyle: {},
  },
  'line-chart': {
    type: 'line-chart',
    name: '折线图',
    category: 'chart',
    icon: 'TrendCharts',
    defaultWidth: 400,
    defaultHeight: 300,
    defaultProps: { title: '折线图', data: [] },
    defaultStyle: {},
  },
  'pie-chart': {
    type: 'pie-chart',
    name: '饼图',
    category: 'chart',
    icon: 'PieChart',
    defaultWidth: 300,
    defaultHeight: 300,
    defaultProps: { title: '饼图', data: [] },
    defaultStyle: {},
  },
  'scatter-chart': {
    type: 'scatter-chart',
    name: '散点图',
    category: 'chart',
    icon: 'DataPoint',
    defaultWidth: 400,
    defaultHeight: 300,
    defaultProps: { title: '散点图', data: [] },
    defaultStyle: {},
  },
  table: {
    type: 'table',
    name: '表格',
    category: 'data',
    icon: 'Grid',
    defaultWidth: 500,
    defaultHeight: 200,
    defaultProps: { columns: [], data: [] },
    defaultStyle: {},
  },
  number: {
    type: 'number',
    name: '数字',
    category: 'info',
    icon: 'Odometer',
    defaultWidth: 100,
    defaultHeight: 60,
    defaultProps: { value: 0, prefix: '', suffix: '', fontSize: 24 },
    defaultStyle: {},
  },
  gauge: {
    type: 'gauge',
    name: '仪表盘',
    category: 'info',
    icon: 'Odometer',
    defaultWidth: 200,
    defaultHeight: 200,
    defaultProps: { value: 50, max: 100 },
    defaultStyle: {},
  },
  progress: {
    type: 'progress',
    name: '进度条',
    category: 'info',
    icon: 'Loading',
    defaultWidth: 300,
    defaultHeight: 20,
    defaultProps: { value: 0, max: 100 },
    defaultStyle: {},
  },
  indicator: {
    type: 'indicator',
    name: '指标卡',
    category: 'info',
    icon: 'Flag',
    defaultWidth: 200,
    defaultHeight: 100,
    defaultProps: { title: '指标', value: 0, unit: '' },
    defaultStyle: {},
  },
}

/** 分类分组后的组件列表 */
export const CATEGORY_GROUPS: Record<string, ComponentMeta[]> = {
  basic: Object.values(COMPONENT_META).filter((m) => m.category === 'basic'),
  chart: Object.values(COMPONENT_META).filter((m) => m.category === 'chart'),
  data: Object.values(COMPONENT_META).filter((m) => m.category === 'data'),
  info: Object.values(COMPONENT_META).filter((m) => m.category === 'info'),
}

/** 分类名称映射 */
export const CATEGORY_LABELS: Record<string, string> = {
  basic: '基础组件',
  chart: '图表组件',
  data: '数据组件',
  info: '信息组件',
}

export function getMeta(type: ComponentType): ComponentMeta | undefined {
  return COMPONENT_META[type]
}
